export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b0c9e8",
        "on-surface": "#171c1f",
        "on-secondary-fixed-variant": "#2e4963",
        "on-secondary": "#ffffff",
        "secondary": "#46617c",
        "tertiary-fixed-dim": "#79d4e2",
        "inverse-surface": "#2c3134",
        "tertiary-container": "#002e34",
        "on-error-container": "#93000a",
        "on-surface-variant": "#43474d",
        "on-background": "#171c1f",
        "tertiary-fixed": "#96f1ff",
        "inverse-primary": "#b0c9e8",
        "surface-variant": "#dfe3e7",
        "error": "#ba1a1a",
        "tertiary": "#00181b",
        "on-tertiary-fixed-variant": "#004f57",
        "on-primary-fixed-variant": "#314863",
        "surface-container-low": "#f0f4f8",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#001d33",
        "on-tertiary-fixed": "#001f24",
        "secondary-fixed-dim": "#aec9e8",
        "surface-tint": "#49607c",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-high": "#e4e9ed",
        "background": "#f6fafe",
        "on-primary": "#ffffff",
        "primary-fixed": "#d1e4ff",
        "outline-variant": "#c3c6ce",
        "on-tertiary-container": "#3c9caa",
        "surface-bright": "#f6fafe",
        "error-container": "#ffdad6",
        "secondary-container": "#c4e0ff",
        "inverse-on-surface": "#edf1f5",
        "outline": "#74777e",
        "primary": "#00152a",
        "on-secondary-container": "#48637e",
        "surface-container-highest": "#dfe3e7",
        "on-primary-container": "#7a92b0",
        "primary-container": "#102a43",
        "surface-dim": "#d6dade",
        "secondary-fixed": "#cfe5ff",
        "surface": "#f6fafe",
        "on-primary-fixed": "#011d35",
        "surface-container": "#eaeef2"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
